spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mail:
    host: smtp.163.com
    username: zhaochanglang12@163.com
    password: BAXEOJCOGGATTGWM
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_python_learn
    username: root
    password:
  redis:
    host: 106.55.103.152
    port: 6379
    database: 0
    password:
    connect-timeout: 10000
    jedis:
      pool:
        max-active: 8

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.example.javapythonstory.code.mapper
server:
  port: 8089